// MainWindowDefs.h
// Generated by Interface Elements (Window v2.2) on Dec 17 1998
// Do not modify this file!



/*

Views in mainWindow:
	"backgroundView"  (BView)
	<unnamed> (BStringView)
	"tempoSlider"  (BSlider)
	"tempoValue"  (BStringView)
	"startButton"  (BButton)
	"copyrightString"  (BStringView)

*/


// Message constants:
enum {
	IE_MAINWINDOW_TEMPOSLIDER = 0x6D657373L,
	IE_MAINWINDOW_STARTBUTTON = 0x1BL
};

